// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1az0XPDYneqBJNSr_iY8v_BwCy_iKk-Y',
    appId: '1:113389600913:web:1a5d623f9054c4ce61ff30',
    messagingSenderId: '113389600913',
    projectId: 'epic-recipe-app',
    authDomain: 'epic-recipe-app.firebaseapp.com',
    storageBucket: 'epic-recipe-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw7didikc2v4LrqSveFpwfusKglWeEYY8',
    appId: '1:113389600913:android:f5d0484f87ed3c0361ff30',
    messagingSenderId: '113389600913',
    projectId: 'epic-recipe-app',
    storageBucket: 'epic-recipe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIHKKfJPPSTfAgCl3ZhSdvYn4KgTw1TQ',
    appId: '1:113389600913:ios:e65783c689130c1861ff30',
    messagingSenderId: '113389600913',
    projectId: 'epic-recipe-app',
    storageBucket: 'epic-recipe-app.firebasestorage.app',
    iosBundleId: 'com.example.epicRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtIHKKfJPPSTfAgCl3ZhSdvYn4KgTw1TQ',
    appId: '1:113389600913:ios:e65783c689130c1861ff30',
    messagingSenderId: '113389600913',
    projectId: 'epic-recipe-app',
    storageBucket: 'epic-recipe-app.firebasestorage.app',
    iosBundleId: 'com.example.epicRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1az0XPDYneqBJNSr_iY8v_BwCy_iKk-Y',
    appId: '1:113389600913:web:dfe8e9b7f775f32661ff30',
    messagingSenderId: '113389600913',
    projectId: 'epic-recipe-app',
    authDomain: 'epic-recipe-app.firebaseapp.com',
    storageBucket: 'epic-recipe-app.firebasestorage.app',
  );
}
